version: '3.3'

# obj 'db' seria o container, a 'image' corresponderia ao 'FROM' do dockerfile 
# envs pegas do .env
services: 
  db:
    image: mysql:5.7
    volumes: 
      - db_data:/var/lib/mysql 
    restart: always
    env_file:
      - ./config/db.env
  
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    env_file:
      - ./config/wp.env

volumes:
  db_data: {}

