version: '3.3'

services:
  db:
    build: ./mysql/
    restart: always
    env_file:
      - ./config/db.env
    ports:
      - "3307:3306"
    networks: 
      - dockercompose

  backend:
    depends_on:
      - db
    build: ./flask/
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - "C:\\Users\\gui_s\\Documents\\workspaces\\ws-vscode\\curso-docker\\bind_mount_compose\\flask:/app"
    networks:
      - dockercompose

networks:
  dockercompose:

    